# https://atcoder.jp/contests/abc039/submissions/764044
read a
cat <<EOM | grep $a | awk '{print $2}'
WBWBWWBWBWBWWBWBWWBW Do
BWBWWBWBWBWWBWBWWBWB Do
WBWWBWBWBWWBWBWWBWBW Re
BWWBWBWBWWBWBWWBWBWB Re
WWBWBWBWWBWBWWBWBWBW Mi
WBWBWBWWBWBWWBWBWBWW Fa
BWBWBWWBWBWWBWBWBWWB Fa
WBWBWWBWBWWBWBWBWWBW So
BWBWWBWBWWBWBWBWWBWB So
WBWWBWBWWBWBWBWWBWBW La
BWWBWBWWBWBWBWWBWBWW La
WWBWBWWBWBWBWWBWBWWB Si
EOM
